### ISSUE TITLE
PHP Fatal error:  Uncaught InvalidArgumentException: MLP Regressor when loading labeled dataset from iterator 

### ISSUE THREAD

**Issue by ghost** [RubixML/ML#99]
**Describe the bug**

Hi there, I just prepared a basic [`dataset/1_1_beginner.csv`](https://github.com/programarivm/pgn-chess-data/blob/master/dataset/1_1_beginner.csv) file in order to train a beginner chess model in batches:

```
php cli/prepare/beginner.php 1 1
```
This CSV file contains the samples and labels of the first game in the database in order to keep things simple.

```
0;34;2;1;40.06;0;563.66
0;36;2;1;40.06;0;574.66
0;36;2;1;40.06;0;574.66
0;33;2;1;40.06;0;565.66
0;32;2;1;40.06;0;568.66
0;31;2;1;40.06;0;570.66
1;30;2;1;40.06;0;569.66
1;29;3;1;40.06;0;542.66
1;31;3;1;40.06;0;543.66
1;29;2;1;39.06;0;567.66
1;31;3;1;39.06;0;563.66
1;31;3;1;39.06;0;563.66
1;32;3;1;39.06;0;566.66
2;28;5.2;1;39.06;0;570.66
...
```

**To Reproduce**

However, a PHP fatal error is thrown when using this CSV to run the [`cli/train/beginner.php`](https://github.com/programarivm/pgn-chess-data/blob/master/cli/train/beginner.php) script:

```php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

use Rubix\ML\PersistentModel;
use Rubix\ML\CrossValidation\Metrics\RSquared;
use Rubix\ML\Datasets\Labeled;
use Rubix\ML\Extractors\CSV;
use Rubix\ML\Extractors\ColumnPicker;
use Rubix\ML\NeuralNet\CostFunctions\LeastSquares;
use Rubix\ML\NeuralNet\Layers\Dense;
use Rubix\ML\NeuralNet\Layers\Activation;
use Rubix\ML\NeuralNet\ActivationFunctions\ReLU;
use Rubix\ML\NeuralNet\Optimizers\RMSProp;
use Rubix\ML\Other\Loggers\Screen;
use Rubix\ML\Persisters\Filesystem;
use Rubix\ML\Regressors\MLPRegressor;

const DATASET_FOLDER = __DIR__.'/../../dataset';
const MODEL_FOLDER = __DIR__.'/../../model';

$extractor = new ColumnPicker(new CSV(DATASET_FOLDER."/{$argv[1]}", false, ';'), [1, 2, 3, 4, 5, 6]);
$dataset = Labeled::fromIterator($extractor);

$mlpRegressor = new MLPRegressor([
    new Dense(100),
    new Activation(new ReLU()),
    new Dense(100),
    new Activation(new ReLU()),
    new Dense(50),
    new Activation(new ReLU()),
    new Dense(50),
    new Activation(new ReLU()),
], 128, new RMSProp(0.001), 1e-3, 100, 1e-5, 3, 0.1, new LeastSquares(), new RSquared());

$estimator = new PersistentModel($mlpRegressor, new Filesystem(MODEL_FOLDER.'/beginner.model'));

$estimator->setLogger(new Screen('beginner'));
$estimator->train($dataset);
$estimator->save();
```

**Unexpected behavior**

```
docker exec -it --user 1000:1000 pgn_chess_data_php_fpm php cli/train/beginner.php 1_1_beginner.csv
PHP Fatal error:  Uncaught InvalidArgumentException: MLP Regressor (hidden_layers: [0: Dense (neurons: 100, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 1: Activation (activation_fn: ReLU), 2: Dense (neurons: 100, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 3: Activation (activation_fn: ReLU), 4: Dense (neurons: 50, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 5: Activation (activation_fn: ReLU), 6: Dense (neurons: 50, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 7: Activation (activation_fn: ReLU)], batch_size: 128, optimizer: RMS Prop (rate: 0.001, decay: 0.1), alpha: 0.001, epochs: 100, min_change: 1.0E-5, window: 3, hold_out: 0.1, cost_fn: Least Squares, metric: R Squared) is not compatible with categorical data types. in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/SamplesAreCompatibleWithEstimator.php:31
Stack trace:
#0 /usr/share/nginx/ in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/SamplesAreCompatibleWithEstimator.php on line 31

Fatal error: Uncaught InvalidArgumentException: MLP Regressor (hidden_layers: [0: Dense (neurons: 100, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 1: Activation (activation_fn: ReLU), 2: Dense (neurons: 100, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 3: Activation (activation_fn: ReLU), 4: Dense (neurons: 50, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 5: Activation (activation_fn: ReLU), 6: Dense (neurons: 50, alpha: 0, bias: true, weight_initializer: He, bias_initializer: Constant (value: 0)), 7: Activation (activation_fn: ReLU)], batch_size: 128, optimizer: RMS Prop (rate: 0.001, decay: 0.1), alpha: 0.001, epochs: 100, min_change: 1.0E-5, window: 3, hold_out: 0.1, cost_fn: Least Squares, metric: R Squared) is not compatible with categorical data types. in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/SamplesAreCompatibleWithEstimator.php:31
Stack trace:
#0 /usr/share/nginx/ in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/SamplesAreCompatibleWithEstimator.php on line 31
```
I am wondering if I am doing something wrong, and your guidance would be very much appreciated.

**Comment by andrewdalpino** [comment]
Yes, it looks like you are forgetting to convert the categorical features you are importing by CSV into continuous features. [MLP](https://docs.rubixml.com/classifiers/multilayer-perceptron.html) does no support categorical features. Since CSV does not encode type information, all data are imported as strings by default. You can use the [Numeric String Converter](https://docs.rubixml.com/transformers/numeric-string-converter.html) or you can store your dataset in a format that does store type information such as NDJSON. Here is a link to the documentation.

https://docs.rubixml.com/extracting-data.html#csv

Let me know if that solves your issue @programarivm

**Comment by ghost** [comment]
Thanks for the response. 

I did this:

```php
<?php

require_once __DIR__ . '/../../vendor/autoload.php';

use Rubix\ML\PersistentModel;
use Rubix\ML\CrossValidation\Metrics\RSquared;
use Rubix\ML\Datasets\Labeled;
use Rubix\ML\Extractors\CSV;
use Rubix\ML\Extractors\ColumnPicker;
use Rubix\ML\NeuralNet\CostFunctions\LeastSquares;
use Rubix\ML\NeuralNet\Layers\Dense;
use Rubix\ML\NeuralNet\Layers\Activation;
use Rubix\ML\NeuralNet\ActivationFunctions\ReLU;
use Rubix\ML\NeuralNet\Optimizers\RMSProp;
use Rubix\ML\Other\Loggers\Screen;
use Rubix\ML\Persisters\Filesystem;
use Rubix\ML\Regressors\MLPRegressor;
use Rubix\ML\Transformers\NumericStringConverter;

const DATASET_FOLDER = __DIR__.'/../../dataset';
const MODEL_FOLDER = __DIR__.'/../../model';

$extractor = new ColumnPicker(new CSV(DATASET_FOLDER."/{$argv[1]}", false, ';'), [1, 2, 3, 4, 5, 6]);

$dataset = Labeled::fromIterator($extractor)
    ->apply(new NumericStringConverter());

$mlpRegressor = new MLPRegressor([
    new Dense(100),
    new Activation(new ReLU()),
    new Dense(100),
    new Activation(new ReLU()),
    new Dense(50),
    new Activation(new ReLU()),
    new Dense(50),
    new Activation(new ReLU()),
], 128, new RMSProp(0.001), 1e-3, 100, 1e-5, 3, 0.1, new LeastSquares(), new RSquared());

$estimator = new PersistentModel($mlpRegressor, new Filesystem(MODEL_FOLDER.'/beginner.model'));

$estimator->setLogger(new Screen('beginner'));
$estimator->train($dataset);
$estimator->save();
```
But still getting a `PHP Fatal error`:

```
docker exec -it --user 1000:1000 pgn_chess_data_php_fpm php cli/train/beginner.php 1_1_beginner.csv
PHP Fatal error:  Uncaught InvalidArgumentException: Regressors require continuous labels, categorical given. in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/LabelsAreCompatibleWithLearner.php:35
Stack trace:
#0 /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Regressors/MLPRegressor.php(373): Rubix\ML\Specifications\LabelsAreCompatibleWithLearner::check(Object(Rubix\ML\Datasets\Labeled), Object(Rubix\ML\Regressors\MLPRegressor))
#1 /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Regressors/MLPRegressor.php(347): Rubix\ML\Regressors\MLPRegressor->partial(Object(Rubix\ML\Datasets\Labeled))
#2 /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/PersistentModel.php(147): Rubix\ML\Regressors\MLPRegressor->train(Object(Rubix\ML\Datasets\Labeled))
#3 /usr/share/nginx/pgn-chess-data/cli/train/beginner.php(42): Rubix\ML\PersistentModel->train(Object(Rubix\ML\Datasets\Labeled))
#4 {main}
  thrown in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/LabelsAreCompatibleWithLearner.php on line 35

Fatal error: Uncaught InvalidArgumentException: Regressors require continuous labels, categorical given. in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/LabelsAreCompatibleWithLearner.php:35
Stack trace:
#0 /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Regressors/MLPRegressor.php(373): Rubix\ML\Specifications\LabelsAreCompatibleWithLearner::check(Object(Rubix\ML\Datasets\Labeled), Object(Rubix\ML\Regressors\MLPRegressor))
#1 /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Regressors/MLPRegressor.php(347): Rubix\ML\Regressors\MLPRegressor->partial(Object(Rubix\ML\Datasets\Labeled))
#2 /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/PersistentModel.php(147): Rubix\ML\Regressors\MLPRegressor->train(Object(Rubix\ML\Datasets\Labeled))
#3 /usr/share/nginx/pgn-chess-data/cli/train/beginner.php(42): Rubix\ML\PersistentModel->train(Object(Rubix\ML\Datasets\Labeled))
#4 {main}
  thrown in /usr/share/nginx/pgn-chess-data/vendor/rubix/ml/src/Specifications/LabelsAreCompatibleWithLearner.php on line 35
```

**Comment by andrewdalpino** [comment]
So now you need to convert the labels to continuous as well ... https://docs.rubixml.com/datasets/labeled.html#transform-labels

```php
$dataset->transformLabels('floatval');
```

Also see the [Representing Your Data](https://docs.rubixml.com/representing-your-data.html) section of the docs for more info on high-level types.

Is there something that is not clear with the documentation @programarivm? Have you tried storing your data in [NDJSON](https://docs.rubixml.com/extracting-data.html#ndjson) format so you don't have to do any type conversion?

**Comment by ghost** [comment]
Thanks for the prompt response!

This is working okay now:

```php
$dataset = Labeled::fromIterator($extractor)
    ->apply(new NumericStringConverter())
    ->transformLabels('floatval');
```

I overlooked transforming data, possibly because I assumed that `NumericStringConverter()` would do the trick.

Just added this CSV example to the docs https://github.com/RubixML/RubixML/pull/100

**Comment by andrewdalpino** [comment]
Yeah transformers only effect the samples in a dataset not the label

It looks like we already had a good example and notes regarding this in the docs. I've gone ahead and tried to clarify it even more in this commit https://github.com/RubixML/RubixML/commit/d13cd3c61d90159b07bbf8b4ea5fdafc955bf352

Thanks for the question!
